name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        timestamp=$(date '+%Y-%m-%d')
        curl https://mars.nasa.gov/maps/location/api/configure/get?mission=M20 | jq . > data/raw/mission_${timestamp}.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
